# NOTE: all general settings shown are set equal to their default behavior so if you want the described functionality you don't need  to override that key

[general]
# will toggle the case of the previous or current word when you press and release shift without hitting any characters in between.
"toggle_case_on" = ["shift"]
# clear_buffer_on: clears the internal buffer of fuzzy chips when you press the windows key
# left,right, up,down are all arrow keys and windows_down test if the windows/meta/gui key is down "alt_down", "ctrl_down" are also options do the same thing for their respective modifier,
# be mindful of however you keyremapper handles keyoverloading if you use one
# for example I use keyd and if I press right shift it will hold down alt if I release it without typing anything else it will type ?
# that means the buffer gets cleared and it would mess with append_chars if I had alt_down in my config to clear the buffer
# Also keep in mind using clear_on_buffer will interfere with toggle_case_on if you put the same key in both
"clear_buffer_on" = ["windows_down", "ctrl_down", "alt_down"]
# same as clear_buffer_on unless using ipc if the buffer was just set by ipc then the event won't clear the buffer
"just_set_safe_clear" = ["up", "down"]
# append_chars have special behavior depending on the setting of auto_append
# if true when pressing an append char it will be automatically appended to the previous word in the buffer and white space will be restored
# if false then it won't append until you press space and will fail to do so if you press shift+space
# you probably don't want to auto append when working with shells and programming
"append_chars" = [".", "!", "?", ",", ";", ")", "]", "}"]
"auto_append" = false
# if the previous word ends with one of these characters then the current word will be capitalized once you hit space
"capitalize_after" = [".", "!", "?"]
# passes through the captlization modifier of the last word so if it is 'hi.' the next word will be captlized
# where as 'hi' it will not
"captlize_passthrough" = ['"', "'", "`"]
# WARNING: these options are a little more complicated
# they allow you to ignore certain leading and trailing characters for chip expansion, for example:
# if you have hv = have, you probably want "hv to expand to "have and "hv" to expand to "have", this allows you to do that without defining extra chips for every case
# complexity occurs when you use one of these characters inside of a chip like using w' = we're.
# in this case if there is an exact match that is you type 'w we will expand the chip if there is not an exact match say you type
# 'w' we will expand as if you had meant to type w between single quotes, so if w = were then you would get 'were' if w isn't mapped to anything you will just get a w in single quotes
# having said that I would generally suggest avoiding ignoring any characters you uese inside of your chips for this very reason.
# or you could remove everything from ignored prefixes and postfixes if you prefer.
# if you are going to do so then avoid defining chips which are single letters when you have a variant with one of the ignore characters.
# for example if you define a chip t= the, I would advise against defining 't = anything.
# these rules only apply to chips which are mapped to strings if a chip maps to a list then it will not obey ignore_leading and ignore_trailing and will only expand for an exact match
"ignored_leading" = ['"', "(", "[", "{", "`", "'"]
"ignored_trailing" = ['"', ")", "]", "}", "`", "'", ".", "!", "?", ","]
# normal-> best for natural language, code-> nice for coding breaks some natural language use cases
# if code spacing is used then the casing of the current word is detected and used
# so if you have something in cammel case like "helloT" and you press space it would expand to "helloThe"
# this breaks the use case like this tH would normally expand to something like That but instead would expand to tHere
# this allows you to modify in the middle of words as well and also supports snake casing, when spacing after typing something at the
# end of a snake cased variable it will type an _ until you hit space again
# so hello_there+space becomes hello_there_ if you do space again it becomes "hello_there "
# if you press space when doing cammel case if it wouldn't change anything then it will just put a space between the words or afterwards if it would expand something then it will expand and not insert a space
# propercase and UPPER_SNAKE_CASE are also detected and supported kebab is not currently
"spacing_type" = "normal"

[ipc]
# uses a tcp socket
port = 8765
host = "127.0.0.1"  # local host, I can't think of a reason to change this but it's here
# commands that can be sent through ipc, all disabled by default
# works nicely with this neovim plugin: https://github.com/Ben-Collett/chipped.nvim
# do keep in mind any program can access these commands even a malicouse one(theoretically atleast)
# highly unlikely for a attack area since most commands can't really be used in a very harmful way for most users
# plus pretty much no one is using fuzzy chips so there is no inscentive to try to exploit it.
ipc_enabled_commands = [
  # With thee commands a prakster could theortically prevent you from typing in normal mode with this I guess
  # though why they would I don't know, and it is pretty pointless if you have a chip set up to quit the program

  # "mc",  # activate normal casing
  # "sc",  # activate snake_casing
  # "pm",  # activate ProperCasing
  # "cm",  # activate camelCasing
  # "us",  # activate UPPER_SNAKE_CASING
  # I guess a bad actor could force you to type the wrong chip if they had these commands...
  # "cb",  # clear buffer
  # "sm",  # set main buffer
  # "sr",  # set right buffer

  # WARNING: the below are more exploitable
  # for example I could change your config file and change chips to something else if I where a malisouce actor with rl and rs
  # like if you used a crypto wallett or something like that it could be bad.

  # although a bad actor with the remote code execution required to do that could probably do worse...
  # "rl",  # reload config
  # "rs",  # restart program
]

# chips can be a list of keys or a string of characters, if its a list each element must be a valid key name
# if it is a string then space will be automatically added at the end when triggering the chip this is not true for list in that case you must end with a space key if you want to space
[chips]
# examples using a list very nice for after you type something like th for that and then hitting 's to make that's
"'s" = ["backspace", "'", "s", "space"]
"n't" = ["backspace", "n", "'", "t", "space"]
"'l" = ["backspace", "'", "l", "l", "space"]
"rl" = ["reload_config"]
"qui" = ["quit"]
"ras" = ["restart"]
"cl" = ["clear_buffer"]
"-" = ["kebab-case-mode"]
"nm" = ["normal case mode"]
"_" = ["snake_case_mode"]
"__" = ["UPPER_SNAKE_CASE_MODE"]
"pm" = ["ProperCaseMode"]
"cmm" = ["camelCaseMode"]
# "c(" = ["backspace", "shift", "(", ")"] # buged doesn't handle captlizeding for ()
# "tpw" = [
#   "prev_word_toggle_case",
#   "prev_word_toggle_case",
#   "prev_word_toggle_case"
# ]
"t," = "this is dumb, but legal and useful for testing"  # just keep in mind if you do this and you have auto append on and , set to append you better hit t before ,
# you can use to to make typing a word order independent, example ta = at or toni = into
"at" = "at"
"it" = "it"
"in" = "in"
# I on it's own is always captlized(if your not doing coding/math)
"i" = "I"
# abbreviations for speed, they can even be a single letter!
"d" = "and"
"r" = "are"
# or reuse letters
"ppl" = "people"
# you can also map to multiple words
"mws" = "this is multiple words isn't that cool"
# keep in mind since order doesn't matter you probably don't want to overried on to be on since it is the same as no
"o" = "on"
"n" = "no"
# You can use non-letters just keep in mind your ignored prefixes and postfixes
"w'" = "we're"
# ================== nothing new below this point just more examples ===============================
"is" = "is"
"of" = "of"
"to" = "to"
"so" = "so"
"be" = "be"
"into" = "into"
"do" = "do"
"us" = "us"
"an" = "an"
"by" = "by"
"up" = "up"
"or" = "or"
"go" = "go"
"he" = "he"
"me" = "me"
"if" = "if"
"we" = "we"
"as" = "as"
"am" = "am"
"my" = "my"
"his" = "his"
"now" = "now"
"y" = "you"
"f" = "for"
"g" = "get"
"c" = "can"
"b" = "be"
"t" = "the"
"tt" = "the"
"js" = "just"
"nv" = "never"
"th" = "that"
"bu" = "but"
"ar" = "are"
"nt" = "not"
"yr" = "your"
"al" = "all"
"hv" = "have"
"aw" = "was"
"ts" = "this"
"wt" = "what"
"ty" = "they"
"wn" = "when"
"kw" = "know"
"oe" = "one"
"tr" = "there"
"lk" = "like"
"wi" = "will"
"ig" = "it's"
"dn" = "don't"
"im" = "I'm"
"iv" = "I've"
"lf" = "life"
"tm" = "time"
"ow" = "who"
"ou" = "out"
"et" = "them"
"ab" = "about"
"mr" = "more"
"yo" = "you're"
"hd" = "had"
"ur" = "our"
"ly" = "only"
"hw" = "how"
"tg" = "thing"
"eg" = "enough"
"se" = "see"
"rw" = "were"
"lv" = "live"
"ov" = "love"
"jt" = "than"
"ei" = "their"
"bj" = "because"
"bk" = "back"
"bl" = "black"
"bh" = "behind"
"bo" = "before"
"tk" = "think"
"mk" = "make"
"en" = "then"
"sm" = "some"
"sg" = "something"
"bn" = "been"
"ej" = "end"
"ev" = "even"
"wy" = "way"
"hm" = "him"
"cu" = "could"
"dy" = "day"
"hs" = "has"
"oj" = "other"
"aj" = "another"
"ys" = "yes"
"ye" = "you're"
"yv" = "you've"
"di" = "did"
"wht" = "with"
"wnt" = "want"
"ghs" = "things"
"wor" = "word"
"wrl" = "world"
"wul" = "would"
"frm" = "from"
"dif" = "different"
