# NOTE: all settings besideds the chips section at the bottom of the file are set equal to their default behavior so if you want the described functionality you don't need  to override that key

[general]
# if the previous word ends with one of these characters then the current word will be capitalized once you hit space
# set to an empty list to avoid any auto captlizing
# capitalize_after = []
capitalize_after = [".", "!", "?"]

# append_chars have special behavior depending on the setting of auto_append
# if true when pressing an append char it will be automatically appended to the previous word in the buffer and white space will be restored
# if false then it won't append until you press space and will fail to do so if you press shift+space
# you probably don't want to auto append when working with shells and programming
append_chars = [".", "!", "?", ",", ";", ")", "]", "}"]
auto_append = false

# the maximum capacity for the internal buffer in fuzzy chips
# defaults to 500 or that is to say up to the last 500
# key events are stored if you set it to 0 or less then the buffer will have unlimited capacity
# but if you do that and never clear the buffer it is a memory leak
buffer_size = 500

# the following 4 sections define allow you to define actions based on certain keyboarnd and mouse conditions.
# NOTE: in toml any key that has a special symbol like a + needs to be in quotes
# these are the available commands: clear_buffer, clear_buffer_ipc_safe, delete_word, toggle_casing, expand
# this is also the order of precedence if a binding would have both deleted a word and expanded an expression delete_word will run expand will not
# clear buffer clears the internal buffer used by fuzzy chips
# clear buffer ipc safe clears the internal buffer used by fuzzy chips unless it was just set via ipc
# delete_word backspaces the previous/current word based on the buffer
# toggle_case toggles the previous word between upper and lowwer case unless there is a non leading underscore then it will toggle the captlization of the whole word
# expand: expands the current word based on the buffer also handles appending punctuation if autoexpand is false

# the on_press section triggers when an exact hotkey is pressed that is to say
# if you put space as a key it will trigger if you press space but not if you press shift+space unless that is explicitly also a key
[on_press]
space = "expand"
# enter = "expand" # expand when you preess enter/return, annoying for coding.
# "shift+space" = "expand" # expand when you press shift+space, that way it is harder to accidentally expand
"shift+backspace" = "delete_word"
# these two should probably always be set to this
up = "clear_buffer_ipc_safe"
down = "clear_buffer_ipc_safe"

# on toggle triggers when a key is pressed and then released without pressing any keys in between.
# this must be a single key like shift or alt not a hotkey
[on_toggle]
shift = "toggle_case"

# while_down triggers whenever you press any key while one of these keys are down
# can only be applied to ctrl, alt, and windows
# fair warning to keyd users if you use overload(alt,whatever) with keyd it will also press control
# when you release the key without pressing any other keys. That is to avoid triggering a hotkey in firefox I think.
[while_down]
windows = "clear_buffer"
ctrl = "clear_buffer"
alt = "clear_buffer"

# triggers when a certain mouse button is pressed, left, right, X1, X2, maybe middle or wheel TODO: look into wheel/middle
# in any case the main functionality you would want with this is clearing the buffer when you left click
[on_mouse_button_down]
left = "clear_buffer"

[chunking]
# none, last, all
# all will expand all chunks in the last word
# example: t-tg-th->the-thing-that, assuming t->the tg->thing th->that
# last will only expand the last word and is the default behavior, although witching to all can be faster for certain workflows, it is easier to mess up using
# none of disable chunking as it can get in the way if you type a lot of equations
chunking_type = "last"
# will only expand chunk that are new so if where in all mode and you typed "t-tg-th" and you did a non-expanding space(shift+space by default) then backspaced back and add -ab-tg only the last part would expand
# so t-tg-th-about-again
# this setting is generally advisiable if your using a external program or plugin for your text editor to sync the buffer with your current text
new_chunks_only = false
# non alphanumeric characters treated as alphanumeric characters for chunking, ' that way contractions like that's wont expand
# if you are using things like code casing  likely want _ in the chunking_ignore section
# while chunking with _ works fine in the forward direction it is not as effective for editing snake case code in post as dedicated code casing and new casing modes
chunking_ignore = ["'", "_"]

[rare]
# these settings can be changed but rarely should
# passes through the captlization modifier of the last word so if it is 'hi.' the next word will be captlized
# where as 'hi' it will not
captlize_passthrough = ["\"", "'", "`"]

[code]
# WARNING: these setting does nothing when not in normal casing mode.
# normal -> best for natural language
# code -> nice for coding breaks some natural language use cases
# new -> also nice for coding work well with fuzzychips and with chording systems.

# if code spacing is used then the casing of the current word is detected and used
# so if you have something in cammel case like "helloT" and you press space it would expand to "helloThe"
# this breaks the use case like this tH would normally expand to something like That but instead would expand to tHere
# this allows you to modify in the middle of words as well and also supports snake casing, when spacing after typing something at the
# end of a snake cased variable it will type an _ until you hit space again

# so hello_there+space becomes hello_there_ if you do space again it becomes "hello_there "
# if you press space when doing cammel case if it wouldn't change anything then it will just put a space between the words or afterwards if it would expand something then it will expand and not insert a space
# propercase and UPPER_SNAKE_CASE are also detected and supported kebab is not currently

# new spacing works similar to code spacing except it uses only new characters typed and will treat the new characters typed as a whole word
# so if you have hello_there_person
# and you type hello_th<t space>ere_person it will expand to hello_th_the_ere_person
# cammel,snake,UPPER_SNAKE,ProperCase, normal are all supported
spacing_type = "normal"

# this setting only applies to new mode, everything typed except when detected otherwise will be assumed to be in this mode
# ex: if it is set to cammel casing then "hello_there<t space>" will still expand to hello_there_the
# however "hello<t space>" will expand to helloThe
# values snake, camel, upper snake, normal
assumed_casing = "normal"

# space on new is when true measn that if nothing chegss as a result of hitting space when using new mode it will just space forward
# the only real reason to them this to false is if you are using charachroder with autocorrect it can be convenient since you would have to use
# two spaces to move forward instead of one when dealing with code so autocorrect won't backspace your regular text
space_on_new = true

[ipc]
# uses a tcp socket
port = 8765
host = "127.0.0.1"

# commands that can be sent through ipc, all disabled by default
# works nicely with this neovim plugin: https://github.com/Ben-Collett/chipped.nvim
# do keep in mind any program can access these commands even a malicouse one(theoretically atleast)
# highly unlikely for a attack area since most commands can't really be used in a very harmful way for most users
# plus pretty much no one is using fuzzy chips so there is no inscentive to try to exploit it.

ipc_enabled_commands = [
  # With thee commands a prakster could theortically prevent you from typing in normal mode with this I guess
  # though why they would I don't know, and it is pretty pointless if you have a chip set up to quit the program

  # "mc",  # activate normal casing
  # "sc",  # activate snake_casing
  # "pm",  # activate ProperCasing
  # "cm",  # activate camelCasing
  # "us",  # activate UPPER_SNAKE_CASING
  # I guess a bad actor could force you to type the wrong chip if they had these commands...
  # "cb",  # clear buffer
  # "sm",  # set main buffer
  # "sr",  # set right buffer

  # WARNING: the below are more exploitable
  # for example I could change your config file and change chips to something else if I where a malisouce actor with rl and rs
  # like if you used a crypto wallett or something like that it could be bad.

  # although a bad actor with the remote code execution required to do that could probably do worse...
  # "rl",  # reload config "rs",  # restart program
]

[chips]
# chips can be a list of keys or a string of characters, if its a list each element must be a valid key name
# if it is a string then space will be automatically added at the end when triggering the chip this is not true for list in that case you must end with a space key if you want to space
# examples using a list very nice for after you type something like th for that and then hitting 's to make that's
"'s" = ["backspace", "'", "s", "space"]
"n't" = ["backspace", "n", "'", "t", "space"]
"'l" = ["backspace", "'", "l", "l", "space"]

rl = ["reload_config"]
qui = ["quit"]
ras = ["restart"]
cl = ["clear_buffer"]

"-" = ["kebab-case-mode"]
nm = ["normal case mode"]
_ = ["snake_case_mode"]
__ = ["UPPER_SNAKE_CASE_MODE"]
pm = ["ProperCaseMode"]
cmm = ["camelCaseMode"]

"t," = "this is dumb, but legal and useful for testing"
# you can use to to make typing a word order independent, example ta = at or toni = into
at = "at"
it = "it"
in = "in"

# I on it's own is always captlized(if your not doing coding/math)
i = "I"
# abbreviations for speed, they can even be a single letter!
d = "and"
r = "are"
# or reuse letters
ppl = "people"
# you can also map to multiple words
mws = "this is multiple words isn't that cool"
# keep in mind since order doesn't matter you probably don't want to overried on to be on since it is the same as no
o = "on"
n = "no"

# You can use non-letters just keep in mind your ignored prefixes and postfixes
"w'" = "we're"
# =================== nothing new below this point just more examples ===============================
is = "is"
of = "of"
to = "to"
so = "so"
be = "be"
into = "into"
do = "do"
us = "us"
an = "an"
by = "by"
up = "up"
or = "or"
ag = "anything"
go = "go"
he = "he"
me = "me"
if = "if"
we = "we"
as = "as"
am = "am"
my = "my"
his = "his"
now = "now"
y = "you"
f = "for"
g = "get"
c = "can"
b = "be"
t = "the"
tt = "the"
js = "just"
nv = "never"
th = "that"
bu = "but"
ar = "are"
nt = "not"
yr = "your"
al = "all"
hv = "have"
aw = "was"
ts = "this"
wt = "what"
ty = "they"
wn = "when"
kw = "know"
oe = "one"
tr = "there"
lk = "like"
wi = "will"
ig = "it's"
dn = "don't"
im = "I'm"
iv = "I've"
lf = "life"
tm = "time"
ow = "who"
ou = "out"
et = "them"
ab = "about"
mr = "more"
yo = "you're"
hd = "had"
ur = "our"
ly = "only"
hw = "how"
tg = "thing"
eg = "enough"
se = "see"
rw = "were"
lv = "live"
ov = "love"
jt = "than"
ei = "their"
bj = "because"
bk = "back"
bl = "black"
bh = "behind"
bo = "before"
tk = "think"
mk = "make"
en = "then"
sm = "some"
sg = "something"
bn = "been"
ej = "end"
ev = "even"
wy = "way"
hm = "him"
cu = "could"
dy = "day"
hs = "has"
oj = "other"
aj = "another"
ys = "yes"
ye = "you're"
yv = "you've"
di = "did"
wht = "with"
wnt = "want"
ghs = "things"
wor = "word"
wrl = "world"
wul = "would"
frm = "from"
dif = "different"

