#!/usr/bin/env python3
"""
Validates that example_config.toml and config.py match the expected structure
generated by gen_common.py
"""

import sys
import os
from pathlib import Path

dev_tools_dir = Path(__file__).resolve().parent
sys.path.insert(0, str(dev_tools_dir))


def normalize_content(content: str) -> str:
    lines = [line.rstrip() for line in content.splitlines()]
    while lines and not lines[-1]:
        lines.pop()
    lines.append('')
    return '\n'.join(lines)


def validate_file_exists(filepath: str, description: str) -> bool:
    if not os.path.exists(filepath):
        print(f"ERROR: {description} not found: {filepath}")
        return False
    print(f"OK: {description} exists: {filepath}")
    return True


def validate_toml_structure() -> bool:
    print("\n--- Validating example_config.toml ---")
    try:
        from gen_common import make_builder, example_config_path, make_toml
    except ImportError as e:
        print(f"ERROR: Cannot import from gen_common: {e}")
        return False

    toml_path = example_config_path()
    if not validate_file_exists(toml_path, "example_config.toml"):
        return False

    try:
        builder = make_builder()
        expected_toml = make_toml(builder)
    except Exception as e:
        print(f"ERROR: Failed to generate expected TOML: {e}")
        return False

    with open(toml_path, 'r') as f:
        actual_toml = f.read()

    expected_normalized = normalize_content(expected_toml)
    actual_normalized = normalize_content(actual_toml)

    if expected_normalized == actual_normalized:
        print("OK: example_config.toml matches expected structure")
        return True

    print("ERROR: example_config.toml does not match expected structure")
    expected_lines = expected_normalized.splitlines()
    actual_lines = actual_normalized.splitlines()
    diff_count = 0
    for i, (exp_line, act_line) in enumerate(zip(expected_lines, actual_lines)):
        if exp_line != act_line:
            print(f"  Line {i+1}:")
            print(f"    Expected: {repr(exp_line)}")
            print(f"    Actual:   {repr(act_line)}")
            diff_count += 1
            if diff_count >= 10:
                break
    if len(expected_lines) != len(actual_lines):
        print(f"  Length difference: expected {len(expected_lines)}, actual {len(actual_lines)}")
    return False


def validate_python_structure() -> bool:
    print("\n--- Validating config.py ---")
    try:
        from gen_common import make_builder, python_path, make_python
    except ImportError as e:
        print(f"ERROR: Cannot import from gen_common: {e}")
        return False

    py_path = python_path()
    if not validate_file_exists(py_path, "config.py"):
        return False

    try:
        builder = make_builder()
        expected_python = make_python(builder)
    except Exception as e:
        print(f"ERROR: Failed to generate expected Python: {e}")
        return False

    with open(py_path, 'r') as f:
        actual_python = f.read()

    expected_normalized = normalize_content(expected_python)
    actual_normalized = normalize_content(actual_python)

    if expected_normalized == actual_normalized:
        print("OK: config.py matches expected structure")
        return True

    print("ERROR: config.py does not match expected structure")
    expected_lines = expected_normalized.splitlines()
    actual_lines = actual_normalized.splitlines()
    diff_count = 0
    for i, (exp_line, act_line) in enumerate(zip(expected_lines, actual_lines)):
        if exp_line != act_line:
            print(f"  Line {i+1}:")
            print(f"    Expected: {repr(exp_line)}")
            print(f"    Actual:   {repr(act_line)}")
            diff_count += 1
            if diff_count >= 10:
                break
    if len(expected_lines) != len(actual_lines):
        print(f"  Length difference: expected {len(expected_lines)}, actual {len(actual_lines)}")
    return False


def main():
    print("Validating config structure...")
    toml_ok = validate_toml_structure()
    python_ok = validate_python_structure()

    print("\n--- Summary ---")
    if toml_ok and python_ok:
        print("SUCCESS: All files match expected structure")
        return 0
    print("FAILURE: Some files do not match expected structure")
    if not toml_ok:
        print("  - example_config.toml: MISMATCH")
    if not python_ok:
        print("  - config.py: MISMATCH")
    return 1


if __name__ == "__main__":
    sys.exit(main())
